### ISSUE TITLE
Unable to Telnet "Telnet received DONT Echo (1)"

### ISSUE THREAD

**Issue by DilrajSK** [davidbombal/pythonvideos#6]
Hi David,

I am unable to establish a connection by using the PythonR1Script1. I am getting an error as mentioned in the title.

The debug is as below:

*Mar  1 00:05:25.199: Telnet130: 1 1 251 1
*Mar  1 00:05:25.199: TCP130: Telnet sent WILL ECHO (1)
*Mar  1 00:05:25.199: Telnet130: 2 2 251 3
*Mar  1 00:05:25.199: TCP130: Telnet sent WILL SUPPRESS-GA (3)
*Mar  1 00:05:25.199: Telnet130: 80000 80000 253 24
*Mar  1 00:05:25.203: TCP130: Telnet sent DO TTY-TYPE (24)
*Mar  1 00:05:25.203: Telnet130: 10000000 10000000 253 31
*Mar  1 00:05:25.203: TCP130: Telnet sent DO WINDOW-SIZE (31)
*Mar  1 00:05:25.315: TCP130: Telnet received DONT ECHO (1)
*Mar  1 00:05:25.315: TCP130: Telnet sent WONT ECHO (1)
*Mar  1 00:05:25.395: TCP130: Telnet received DONT SUPPRESS-GA (3)
*Mar  1 00:05:25.395: TCP130: Telnet sent WONT SUPPRESS-GA (3)
R1#
*Mar  1 00:05:25.399: TCP130: Telnet received WONT TTY-TYPE (24)
*Mar  1 00:05:25.399: TCP130: Telnet sent DONT TTY-TYPE (24)
*Mar  1 00:05:25.399: TCP130: Telnet received WONT WINDOW-SIZE (31)
*Mar  1 00:05:25.403: TCP130: Telnet sent DONT WINDOW-SIZE (31)
*Mar  1 00:05:25.483: TCP130: Telnet received DONT ECHO (1)
*Mar  1 00:05:25.699: TCP130: Telnet received DONT SUPPRESS-GA (3)
*Mar  1 00:05:25.699: TCP130: Telnet received WONT TTY-TYPE (24)
*Mar  1 00:05:25.699: TCP130: Telnet received WONT WINDOW-SIZE (31)

The telnet is working fine without the script from the same machine. Below is the debug for that:

*Mar  1 00:04:16.911: Telnet130: 1 1 251 1
*Mar  1 00:04:16.911: TCP130: Telnet sent WILL ECHO (1)
*Mar  1 00:04:16.911: Telnet130: 2 2 251 3
*Mar  1 00:04:16.911: TCP130: Telnet sent WILL SUPPRESS-GA (3)
*Mar  1 00:04:16.911: Telnet130: 80000 80000 253 24
*Mar  1 00:04:16.915: TCP130: Telnet sent DO TTY-TYPE (24)
*Mar  1 00:04:16.915: Telnet130: 10000000 10000000 253 31
*Mar  1 00:04:16.915: TCP130: Telnet sent DO WINDOW-SIZE (31)
*Mar  1 00:04:16.935: TCP130: Telnet received DO SUPPRESS-GA (3)
*Mar  1 00:04:16.935: TCP130: Telnet received WILL TTY-TYPE (24)
*Mar  1 00:04:16.935: Telnet130: Sent SB 24 1
*Mar  1 00:04:16.939: TCP130: Telnet received WILL WINDOW-SIZE (31)
*Mar  1 00:04:16.939: TCP130: Telnet received WILL TTY-SPEED (32) (refused)
*Mar  1 00:04:16.939: TCP130: Telnet sent DONT TTY-SPEED (32)
*Mar  1 00:04:16.939: TCP130: Telnet received WILL LOCAL-FLOW (33)
*Mar  1 00:04:16.943: TCP130: Telnet sent DO LOCAL-FLOW (33)
*Mar  1 00:04:16.943: Telnet130: Sent SB 33 0
*Mar  1 00:04:16.943: TCP130: Telnet received WILL LINEMODE (34)
*Mar  1 00:04:16.947: TCP130: Telnet sent DONT LINEMODE (34) (unimplemented)
*Mar  1 00:04:16.947: TCP130: Telnet received WILL NEW-ENVIRON (39)
*Mar  1 00:04:16.947: TCP130: Telnet sent DONT NEW-ENVIRON (39) (unimplemented)
*Mar  1 00:04:16.951: TCP130: Telnet received DO STATUS (5)
*Mar  1 00:04:16.951: TCP130: Telnet sent WONT STATUS (5) (unimplemented)
*Mar  1 00:04:16.951: TCP130: Telnet received WILL X-DISPLAY (35) (refused)
*Mar  1 00:04:16.955: TCP130: Telnet sent DONT X-DISPLAY (35)
*Mar  1 00:04:17.039: TCP130: Telnet received DO ECHO (1)
*Mar  1 00:04:17.039: Telnet130: recv SB NAWS 80 24
*Mar  1 00:04:17.043: Telnet130: recv SB 24 0 xterm-256color

Your inputs on this would be highly appreciated.

Regards,
DILRAJ

**Comment by DilrajSK** [comment]
Issue is fixed

**Comment by Futurackzz** [comment]
i am facing the same issue , how did you resolve it
